services:
  - type: web
    name: afcyber-solutions-platform
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///instance/afcyber_platform.db
      - key: ADMIN_EMAIL
        value: admin@afcybersolutions.com.do
      - key: ADMIN_PASSWORD
        sync: false
